console.log("code is runnning ");
console.log(document.body);
console.log(document.body.childNodes);
console.log(document.body.childNodes[0]);
console.log(document.body.childNodes[1]);
console.log(document.body.childNodes[1].childNodes);
console.log(document.body.childNodes[1].firstChild);
console.log(document.body.childNodes[1].lastChild);
console.log(document.body.firstElementChild);
console.log(document.body.firstElementChild.firstChild);
console.log(document.body.firstElementChild.firstElementChild);
let c=document.body.firstElementChild.firstElementChild;
let d=document.body.firstElementChild.lastElementChild;
document.body.style.backgroundColor="yellow";
c.style.backgroundColor="aqua";
c.parentElement.style.backgroundColor="red";
console.log(c.parentElement);
console.log(d.previousSibling);
console.log(d.previousElementSibling);
d.previousElementSibling.style.backgroundColor="green";
console.log(document.body.firstElementChild.children);
console.log(document.body.firstElementChild.children[3]);
console.log(document.body.children[1]);
console.log(document.body.children[1].rows);
console.log(document.body.children[1].rows[1]);
console.log(document.body.children[1].rows[1].cells);
console.log(document.body.children[1].columns);

// e.style.backgroundColor="white";

